# Generated by Django 4.1.5 on 2023-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localiquizapp', '0002_quiz_description_quiz_ending_quiz_starting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ending',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='starting',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
