# Generated by Django 4.1.5 on 2023-01-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localiquizapp', '0004_alter_quiz_description_alter_quiz_ending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ending',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='starting',
        ),
    ]
